# Generated by Django 6.0.2 on 2026-03-20 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional'), ('completion', 'Completion'), ('achievement', 'Achievement'), ('participation', 'Participation'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('canvas_json', models.JSONField(default=dict, help_text='Fabric.js canvas JSON data')),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('width', models.IntegerField(default=1000)),
                ('height', models.IntegerField(default=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('extra_data', models.JSONField(default=dict, help_text='Additional CSV fields used in template')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS Content ID', max_length=255)),
                ('ipfs_url', models.URLField(blank=True)),
                ('cert_hash', models.CharField(blank=True, help_text='SHA-256 hash of certificate', max_length=66)),
                ('tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66)),
                ('wallet_signature', models.TextField(blank=True, help_text='MetaMask signature of hash')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('verification_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
